services:
  - type: web
    name: shoe-store-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        value: ShoeStore2023SecretKey
      - key: MONGODB_URI
        sync: false
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /admin/*
        destination: /admin/$1
      - type: rewrite
        source: /*
        destination: /index.html

  - type: static
    name: shoe-store-frontend
    buildCommand: echo "Static site"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /admin/*
        destination: /admin/$1
      - type: rewrite
        source: /*
        destination: /index.html
