services:
  - type: web
    name: shoe-store-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080

  - type: static
    name: shoe-store-frontend
    buildCommand: echo "Static site"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
